[package]
name = "multiprocessing"
version = "0.1.0"
edition = "2021"

[dependencies]
ctor = "0.1.22"
lazy_static = "1.4.0"
multiprocessing-derive = { path = "multiprocessing-derive" }
paste = "1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.23.1"
openat = "0.1.21"
tokio = { version = "1", features = ["rt", "macros", "fs"], optional = true }
tokio-seqpacket = { version = "0.5.4", optional = true }

[target.'cfg(windows)'.dependencies]
tokio = { version = "1", features = ["rt", "macros", "fs", "io-util"], optional = true }
windows = { version = "0.39.0", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_LibraryLoader",
    "Win32_System_Pipes",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
]}

[features]
tokio = ["dep:tokio", "dep:tokio-seqpacket"]

[[test]]
name = "sync-main"
path = "tests/main.rs"
harness = false

[[test]]
name = "tokio-main"
path = "tests/tokio.rs"
harness = false
